version: '3.8'

services:
  db:
    image: postgres:17
    container_name: weather-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 270792
      POSTGRES_DB: weather_db
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fastapi-weather-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:270792@db:5432/weather_db"
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
